server:
  port: 8081
spring:
  application:
    name: "crediya-apply-ms"

##DB postgres
adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "loan_service"
    schema: "public"
    username: "loan_user"
    password: "loan_pass"
##

##WebClient
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
    endpoint: "/api/users/{id}/exists"
management:
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
##

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "your-very-long-secret-key-that-should-be-at-least-256-bits-long-for-security-purposes-and-should-be-stored-securely"
  issuer: "crediya-auth-ms"